version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: anycable-demo:0.6.4
    volumes:
      - .:/app:cached
    tmpfs:
      - /tmp
  backend: &backend
    <<: *app
    volumes:
      - .:/app:cached
      - assets:/app/public/assets
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/0
      - CABLE_URL=ws://localhost:8080/cable
      - ADAPTER=any_cable
    depends_on:
      - redis
  runner:
    <<: *backend
    stdin_open: true
    tty: true
    command: /bin/bash
    ports:
      - '3000:3000'
      - '3002:3002'
  web:
    <<: *backend
    command: rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      - rpc
      - ws
  rpc:
    <<: *backend
    command: anycable
  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
  ws:
    image: 'anycable/anycable-go:v0.6.4'
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379/0
      - ANYCABLE_RPC_HOST=rpc:50051
    depends_on:
      - redis
      - rpc

volumes:
  redis:
  assets:
